/* Development-only real-browser QA; no deployment or provider invocation. */
'use strict';
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const origin=process.env.QA_ORIGIN||('http://'+['127','0','0','1'].join('.')+':8765');
const out=process.env.QA_OUTPUT||'browser-evidence';
(async()=>{fs.mkdirSync(out,{recursive:true});const browser=await chromium.launch({headless:true,...(process.env.QA_CHROME_CHANNEL?{channel:process.env.QA_CHROME_CHANNEL}:{})});const results=[];
for(const width of [1440,1024,768,390,320]){const page=await browser.newPage({viewport:{width,height:1000}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('request',r=>requests.push(r.url()));page.on('response',r=>{if(r.status()>=400)errors.push('broken asset');});await page.goto(origin);await page.locator('.scenario-option').first().waitFor();
assert.equal(await page.locator('.scenario-option').count(),6);assert.equal(await page.locator('.node').count(),7);
for(const scenario of ['normal','outage','quota','heartbeat','retry','verification']){await page.locator(`[data-scenario="${scenario}"]`).click();let steps=0;while(await page.locator('#step').isEnabled()){await page.locator('#step').click();assert(++steps<12);}assert((await page.locator('#queue').innerText()).includes('AWAITING HUMAN'));assert((await page.locator('#stats').innerText()).includes('Closed'));await page.locator('#resetDemo').click();assert((await page.locator('#stepCount').innerText()).includes('STEP 1'));}
for(const wid of ['worker-01','worker-02','worker-03','worker-04','worker-05','worker-06']){await page.locator(`[data-id="${wid}"]`).click();assert((await page.locator('#inspector').innerText()).includes('Not observable'));}
await page.locator('[data-id="worker-06"]').focus();assert((await page.locator('#inspector').innerText()).includes('Unknown'));assert((await page.locator('[data-id="worker-06"]').evaluate(n=>getComputedStyle(n).outlineStyle))!=='none');
for(const summary of await page.locator('summary').all()){await summary.press('Enter');assert(await summary.evaluate(n=>n.parentElement.open));}
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const clipped=await page.locator('.node').evaluateAll(nodes=>nodes.filter(n=>{const a=n.getBoundingClientRect(),b=n.closest('#graph').getBoundingClientRect();return a.left<b.left-1||a.right>b.right+1||a.top<b.top-1||a.bottom>b.bottom+1;}).length);assert.equal(clipped,0);
await page.locator('[data-scenario="normal"]').click();for(let i=0;i<3;i++)await page.locator('#step').click();await page.locator('#play').click();assert(await page.locator('animateMotion').count()>0);await page.locator('#play').click();assert.equal(await page.locator('animateMotion').count(),0);
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#play').click();assert.equal(await page.locator('animateMotion').count(),0);assert(await page.locator('.worker-icon').evaluateAll(ns=>ns.every(n=>getComputedStyle(n).animationName==='none')));await page.locator('#resetDemo').click();await page.emulateMedia({reducedMotion:'no-preference'});
await page.locator('.core').click();if([1440,768,390].includes(width)){const shot=await page.screenshot({path:path.join(out,`v2-${width}.jpg`),fullPage:true,type:'jpeg',quality:65});console.log(`QA_IMAGE_${width}_BEGIN`);console.log(shot.toString('base64'));console.log(`QA_IMAGE_${width}_END`);}
assert.deepEqual(errors,[]);assert(requests.every(u=>u.startsWith(origin)));results.push({width,scenarios:6,overflow:0,clipped:0,errors:0,requests:requests.length,reduced_motion:'PASS',inspection:'PASS',keyboard:'PASS'});await page.close();}
console.log('Browser version: '+browser.version());await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results));})().catch(e=>{console.error(e);process.exit(1);});
